language: python

python:
    - 2.7
    - 3.5
    - 3.6

matrix:
    include:
        - python: "3.7"
          dist: xenial
        - python: "3.8-dev"
          dist: xenial

install:
    - pip install six==1.10.0 # force here to avoid conflict with zc.recipe.testrunner
    - pip install -U setuptools
    - pip install coveralls coverage
    - pip install zc.buildout
    - buildout bootstrap
    - buildout

script:
    - coverage run bin/test -v1

after_success:
    - coverage combine
    - coveralls

notifications:
    email: false

cache:
  pip: true
  directories:
    - eggs/
